  - name: Update System
    yum:
      name: "*"
      state: latest
  
  - name: Install Git & Utils
    yum:
      name: 
        - git
        - yum-utils
        - wget
        - bzip2
      state: present 
  
  - name: Download EPEL Release
    get_url: 
     url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
     dest: /home/ec2-user/epel-release-latest-7.noarch.rpm

  - name: Install EPEL Release
    yum: 
      name: /home/ec2-user/epel-release-latest-7.noarch.rpm
      state: present
  
  - selinux:
      state: disabled

  - name: Add Docker Repo
    yum_repository:
      name: dockerrepo
      description: Docker Repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7/
      gpgcheck: 1
      gpgkey: https://yum.dockerproject.org/gpg
      
  - name: Enable RHEL extras
    shell: yum-config-manager --enable rhui-REGION-rhel-server-extras
  
  - name: Install Docker
    yum:
      name: docker-engine-17.03.0.ce-1.el7.centos
      state: present

  - name: Run Docker
    service: 
      name: docker 
      state: restarted 
      enabled: yes
  

  - name: Download JAva 8
    shell: |
      wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.rpm
      
  
  - name: Install Java 8
    yum:
      name: /home/ec2-user/jdk-8u171-linux-x64.rpm
      state: present

  - name:  Remove Java 7
    package: 
      name: java-1.7.0-openjdk
      state: absent

  - name: Install Maven 
    shell: |
      cd /usr/local
      wget http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
      tar -xf apache-maven-3.5.3-bin.tar.gz
      sudo ln -s apache-maven-3.5.3  maven
      echo "export M2_HOME=/usr/local/maven" >> /etc/profile.d/maven.sh
      echo "export PATH=/usr/local/maven/bin:${PATH}" >> /etc/profile.d/maven.sh
      source /etc/profile.d/maven.sh

  - name: Install NPM
    shell: curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
  
  - name: Install NPM and Dependencies 
    yum: 
      name: 
        - nodejs
        - gcc 
        - gcc-c++ 
        - make
        - flex 
        - bison 
        - ruby
        - openssl-devel 
        - freetype-devel 
        - fontconfig-devel 
        - libicu-devel 
        - sqlite-devel 
        - libpng-devel 
        - libjpeg-devel
        - bzip2
      state: present
  # - name: Download Repo jenkins
  #   shell: |
  #     wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
  #     rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: Download Jenkins RPM
    get_url:
      url:  https://pkg.jenkins.io/redhat/jenkins-2.122-1.1.noarch.rpm
      dest: /home/ec2-user/jenkins-2.122-1.1.noarch.rpm
  
  - name: Install Jenkins  
    yum: 
      name: /home/ec2-user/jenkins-2.122-1.1.noarch.rpm
      state: present

   # - name: install plugins
  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
      enabled: yes

  - name: Create init.groovy.d
    file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0775
  
  - name: Create user Admin
    copy:
      src: basic-security.groovy
      dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
      owner: jenkins
      group: jenkins
      mode: 0775

  - name: Remove wizard Step 1
    copy: 
      src: jenkins.install.UpgradeWizard.state 
      dest: /var/lib/jenkins/jenkins.install.UpgradeWizard.state 
      owner: jenkins 
      group: jenkins 
      mode: 0644 
    copy: 
      src: jenkins.install.InstallUtil.lastExecVersion 
      dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion 
      owner: jenkins 
      group: jenkins 
      mode: 0644  

  - name: Disable setup wizard Step 2
    jenkins_script:
      script: |
        import static jenkins.model.Jenkins.instance as jenkins
        import jenkins.install.InstallState
        if (!jenkins.installState.isSetupComplete()) {
          InstallState.INITIAL_SETUP_COMPLETED.initializeState()
        }
      user: "admin"
      password: "admin"
    
  - name: Copy Script Installation Plugins
    copy:
      src: plugins-add.groovy
      dest: /var/lib/jenkins/init.groovy.d/plugins-add.groovy
      owner: jenkins
      group: jenkins
      mode: 0775

  
  - name: Copy Pipeline script
    copy:
      src: pipeline.groovy
      dest: /var/lib/jenkins/init.groovy.d/pipeline.groovy
      owner: jenkins
      group: jenkins
      mode: 0775

  - name: Add the user Jenkins to Docker Group
    user:
      name: jenkins
      group: docker

  - name: Restart Jenkins due Plugins Install
    service:
      name: jenkins
      state: restarted

 
